import { Operator, Side } from './types';

export const MAPS = [
  "Clubhouse", "Oregon", "Kafe Dostoyevsky", "Bank", "Consulate", "Chalet", 
  "Border", "Coastline", "Villa", "Nighthaven Labs", "Emerald Plains", "Skyscraper",
  "Lair"
];

export const OPERATORS: Operator[] = [
  // ATTACKERS
  { id: 'sledge', name: 'Sledge', side: Side.ATTACKER, role: ['Soft Breach', 'Flank Watch'], speed: 1, health: 3, gadget: 'Tactical Breaching Hammer', iconType: 'breach' },
  { id: 'thatcher', name: 'Thatcher', side: Side.ATTACKER, role: ['Support', 'Disable'], speed: 1, health: 3, gadget: 'EMP Grenade', iconType: 'support' },
  { id: 'ash', name: 'Ash', side: Side.ATTACKER, role: ['Entry Frag', 'Soft Breach'], speed: 3, health: 1, gadget: 'Breaching Round', iconType: 'entry' },
  { id: 'thermite', name: 'Thermite', side: Side.ATTACKER, role: ['Hard Breach', 'Support'], speed: 2, health: 2, gadget: 'Exothermic Charge', iconType: 'breach' },
  { id: 'twitch', name: 'Twitch', side: Side.ATTACKER, role: ['Intel', 'Disable'], speed: 2, health: 2, gadget: 'Shock Drone', iconType: 'intel' },
  { id: 'montagne', name: 'Montagne', side: Side.ATTACKER, role: ['Shield', 'Support'], speed: 1, health: 3, gadget: 'Le Roc Shield', iconType: 'shield' },
  { id: 'glaz', name: 'Glaz', side: Side.ATTACKER, role: ['Sniper', 'Entry Frag'], speed: 2, health: 2, gadget: 'Flip Sight', iconType: 'entry' },
  { id: 'fuze', name: 'Fuze', side: Side.ATTACKER, role: ['Soft Breach', 'Disable'], speed: 1, health: 3, gadget: 'Cluster Charge', iconType: 'breach' },
  { id: 'blitz', name: 'Blitz', side: Side.ATTACKER, role: ['Shield', 'Entry Frag'], speed: 2, health: 2, gadget: 'Flash Shield', iconType: 'shield' },
  { id: 'iq', name: 'IQ', side: Side.ATTACKER, role: ['Intel', 'Support'], speed: 3, health: 1, gadget: 'Electronics Detector', iconType: 'intel' },
  { id: 'buck', name: 'Buck', side: Side.ATTACKER, role: ['Soft Breach', 'Entry Frag'], speed: 2, health: 2, gadget: 'Skeleton Key', iconType: 'breach' },
  { id: 'hibana', name: 'Hibana', side: Side.ATTACKER, role: ['Hard Breach', 'Entry Frag'], speed: 3, health: 1, gadget: 'X-KAIROS', iconType: 'breach' },
  { id: 'jackal', name: 'Jackal', side: Side.ATTACKER, role: ['Intel', 'Roam Clear'], speed: 2, health: 2, gadget: 'Eyenox Model III', iconType: 'intel' },
  { id: 'ying', name: 'Ying', side: Side.ATTACKER, role: ['Crowd Control', 'Entry Frag'], speed: 2, health: 2, gadget: 'Candela', iconType: 'entry' },
  { id: 'zofia', name: 'Zofia', side: Side.ATTACKER, role: ['Entry Frag', 'Soft Breach'], speed: 1, health: 3, gadget: 'KS79 Lifeline', iconType: 'entry' },
  { id: 'dokkaebi', name: 'Dokkaebi', side: Side.ATTACKER, role: ['Intel', 'Roam Clear'], speed: 3, health: 1, gadget: 'Logic Bomb', iconType: 'intel' },
  { id: 'lion', name: 'Lion', side: Side.ATTACKER, role: ['Intel', 'Crowd Control'], speed: 2, health: 2, gadget: 'EE-ONE-D', iconType: 'intel' },
  { id: 'finka', name: 'Finka', side: Side.ATTACKER, role: ['Support', 'Entry Frag'], speed: 2, health: 2, gadget: 'Adrenal Surge', iconType: 'support' },
  { id: 'maverick', name: 'Maverick', side: Side.ATTACKER, role: ['Hard Breach', 'Support'], speed: 3, health: 1, gadget: 'Blow Torch', iconType: 'breach' },
  { id: 'nomad', name: 'Nomad', side: Side.ATTACKER, role: ['Flank Watch', 'Crowd Control'], speed: 2, health: 2, gadget: 'Airjab', iconType: 'trap' },
  { id: 'gridlock', name: 'Gridlock', side: Side.ATTACKER, role: ['Area Denial', 'Flank Watch'], speed: 1, health: 3, gadget: 'Trax Stingers', iconType: 'trap' },
  { id: 'nokk', name: 'Nøkk', side: Side.ATTACKER, role: ['Entry Frag', 'Stealth'], speed: 2, health: 2, gadget: 'HEL Presence Reduction', iconType: 'entry' },
  { id: 'amaru', name: 'Amaru', side: Side.ATTACKER, role: ['Entry Frag', 'Mobility'], speed: 2, health: 2, gadget: 'Garra Hook', iconType: 'entry' },
  { id: 'kali', name: 'Kali', side: Side.ATTACKER, role: ['Support', 'Sniper'], speed: 2, health: 2, gadget: 'LV Explosive Lance', iconType: 'support' },
  { id: 'iana', name: 'Iana', side: Side.ATTACKER, role: ['Intel', 'Entry Frag'], speed: 2, health: 2, gadget: 'Gemini Replicator', iconType: 'intel' },
  { id: 'ace', name: 'Ace', side: Side.ATTACKER, role: ['Hard Breach', 'Entry Frag'], speed: 2, health: 2, gadget: 'S.E.L.M.A.', iconType: 'breach' },
  { id: 'zero', name: 'Zero', side: Side.ATTACKER, role: ['Intel', 'Support'], speed: 3, health: 1, gadget: 'Argus Launcher', iconType: 'intel' },
  { id: 'osa', name: 'Osa', side: Side.ATTACKER, role: ['Shield', 'Support'], speed: 1, health: 3, gadget: 'Talon-8 Shield', iconType: 'shield' },
  { id: 'brava', name: 'Brava', side: Side.ATTACKER, role: ['Intel', 'Disable'], speed: 3, health: 1, gadget: 'Kludge Drone', iconType: 'intel' },
  { id: 'ram', name: 'Ram', side: Side.ATTACKER, role: ['Soft Breach', 'Vertical'], speed: 1, health: 3, gadget: 'BU-GI Auto Breacher', iconType: 'breach' },
  { id: 'deimos', name: 'Deimos', side: Side.ATTACKER, role: ['Intel', 'Roam Clear'], speed: 2, health: 2, gadget: 'DeathMARK', iconType: 'intel' },
  { id: 'striker', name: 'Striker', side: Side.ATTACKER, role: ['Support', 'Soft Breach'], speed: 2, health: 2, gadget: 'Resourceful Recruit', iconType: 'support' },

  // DEFENDERS
  { id: 'smoke', name: 'Smoke', side: Side.DEFENDER, role: ['Anchor', 'Area Denial'], speed: 2, health: 2, gadget: 'Remote Gas Grenade', iconType: 'trap' },
  { id: 'mute', name: 'Mute', side: Side.DEFENDER, role: ['Anchor', 'Intel Denial'], speed: 2, health: 2, gadget: 'Signal Disruptor', iconType: 'support' },
  { id: 'castle', name: 'Castle', side: Side.DEFENDER, role: ['Anchor', 'Support'], speed: 2, health: 2, gadget: 'Armor Panel', iconType: 'support' },
  { id: 'pulse', name: 'Pulse', side: Side.DEFENDER, role: ['Roamer', 'Intel'], speed: 3, health: 1, gadget: 'Cardiac Sensor', iconType: 'intel' },
  { id: 'doc', name: 'Doc', side: Side.DEFENDER, role: ['Anchor', 'Support'], speed: 1, health: 3, gadget: 'Stim Pistol', iconType: 'support' },
  { id: 'rook', name: 'Rook', side: Side.DEFENDER, role: ['Anchor', 'Support'], speed: 1, health: 3, gadget: 'Armor Pack', iconType: 'support' },
  { id: 'kapkan', name: 'Kapkan', side: Side.DEFENDER, role: ['Trap', 'Intel'], speed: 2, health: 2, gadget: 'EDD Trap', iconType: 'trap' },
  { id: 'tachanka', name: 'Tachanka', side: Side.DEFENDER, role: ['Anchor', 'Area Denial'], speed: 1, health: 3, gadget: 'Shumikha Launcher', iconType: 'breach' },
  { id: 'jager', name: 'Jäger', side: Side.DEFENDER, role: ['Roamer', 'Support'], speed: 2, health: 2, gadget: 'ADS', iconType: 'support' },
  { id: 'bandit', name: 'Bandit', side: Side.DEFENDER, role: ['Roamer', 'Breach Denial'], speed: 3, health: 1, gadget: 'Shock Wire', iconType: 'breach' },
  { id: 'frost', name: 'Frost', side: Side.DEFENDER, role: ['Trap', 'Anchor'], speed: 2, health: 2, gadget: 'Welcome Mat', iconType: 'trap' },
  { id: 'valkyrie', name: 'Valkyrie', side: Side.DEFENDER, role: ['Intel', 'Roamer'], speed: 2, health: 2, gadget: 'Black Eye', iconType: 'intel' },
  { id: 'caveira', name: 'Caveira', side: Side.DEFENDER, role: ['Roamer', 'Intel'], speed: 3, health: 1, gadget: 'Silent Step', iconType: 'entry' },
  { id: 'echo', name: 'Echo', side: Side.DEFENDER, role: ['Anchor', 'Intel'], speed: 2, health: 2, gadget: 'Yokai Drone', iconType: 'intel' },
  { id: 'mira', name: 'Mira', side: Side.DEFENDER, role: ['Anchor', 'Intel'], speed: 1, health: 3, gadget: 'Black Mirror', iconType: 'intel' },
  { id: 'lesion', name: 'Lesion', side: Side.DEFENDER, role: ['Trap', 'Anchor'], speed: 2, health: 2, gadget: 'Gu Mines', iconType: 'trap' },
  { id: 'ela', name: 'Ela', side: Side.DEFENDER, role: ['Roamer', 'Trap'], speed: 2, health: 2, gadget: 'Grzmot Mine', iconType: 'trap' },
  { id: 'vigil', name: 'Vigil', side: Side.DEFENDER, role: ['Roamer', 'Intel Denial'], speed: 3, health: 1, gadget: 'ERC-7', iconType: 'entry' },
  { id: 'maestro', name: 'Maestro', side: Side.DEFENDER, role: ['Anchor', 'Intel'], speed: 1, health: 3, gadget: 'Evil Eye', iconType: 'intel' },
  { id: 'alibi', name: 'Alibi', side: Side.DEFENDER, role: ['Roamer', 'Intel'], speed: 3, health: 1, gadget: 'Prisma', iconType: 'intel' },
  { id: 'clash', name: 'Clash', side: Side.DEFENDER, role: ['Shield', 'Crowd Control'], speed: 1, health: 3, gadget: 'CCE Shield', iconType: 'shield' },
  { id: 'kaid', name: 'Kaid', side: Side.DEFENDER, role: ['Anchor', 'Breach Denial'], speed: 1, health: 3, gadget: 'Electroclaw', iconType: 'support' },
  { id: 'mozzie', name: 'Mozzie', side: Side.DEFENDER, role: ['Roamer', 'Intel Denial'], speed: 2, health: 2, gadget: 'Pest Launcher', iconType: 'intel' },
  { id: 'wamai', name: 'Wamai', side: Side.DEFENDER, role: ['Anchor', 'Support'], speed: 2, health: 2, gadget: 'Mag-NET', iconType: 'support' },
  { id: 'oryx', name: 'Oryx', side: Side.DEFENDER, role: ['Roamer', 'Mobility'], speed: 2, health: 2, gadget: 'Remah Dash', iconType: 'entry' },
  { id: 'melusi', name: 'Melusi', side: Side.DEFENDER, role: ['Anchor', 'Crowd Control'], speed: 1, health: 3, gadget: 'Banshee', iconType: 'trap' },
  { id: 'aruni', name: 'Aruni', side: Side.DEFENDER, role: ['Anchor', 'Area Denial'], speed: 1, health: 3, gadget: 'Surya Gate', iconType: 'trap' },
  { id: 'azami', name: 'Azami', side: Side.DEFENDER, role: ['Anchor', 'Support'], speed: 2, health: 2, gadget: 'Kiba Barrier', iconType: 'support' },
  { id: 'solis', name: 'Solis', side: Side.DEFENDER, role: ['Roamer', 'Intel'], speed: 2, health: 2, gadget: 'SPEC-IO Sensor', iconType: 'intel' },
  { id: 'fenrir', name: 'Fenrir', side: Side.DEFENDER, role: ['Trap', 'Crowd Control'], speed: 2, health: 2, gadget: 'F-NATT Mines', iconType: 'trap' },
  { id: 'tubarao', name: 'Tubarão', side: Side.DEFENDER, role: ['Anchor', 'Support'], speed: 2, health: 2, gadget: 'Zoto Canister', iconType: 'support' },
  { id: 'sentry', name: 'Sentry', side: Side.DEFENDER, role: ['Anchor', 'Support'], speed: 2, health: 2, gadget: 'Versatile Defense', iconType: 'support' },
  { id: 'skopos', name: 'Skopós', side: Side.DEFENDER, role: ['Anchor', 'Intel'], speed: 2, health: 2, gadget: 'V10 Pantheon Shells', iconType: 'intel' },
];